CREATE TABLE STUDENT(
Roll_no INT,Name VARCHAR(20),DeptNo INT,Marks INT,Email_id VARCHAR(20),
PRIMARY KEY(Roll_no)
);

INSERT INTO STUDENT VALUES(12,'Ram',101,43,'ram@gmail.com');
INSERT INTO STUDENT VALUES(7,'Asif',102,32,'asif@gmail.com');
INSERT INTO STUDENT VALUES(22,'Niel',103,49,NULL);
INSERT INTO STUDENT VALUES(4,'Vinay',101,30,'vinay@gmail.com');

ALTER table STUDENT ADD
dateofbirth DATE;
--DATE 'YYYY-MM-DD'
UPDATE STUDENT
SET dateofbirth=DATE '2000-10-25';

ALTER TABLE STUDENT DROP COLUMN dateofbirth;

UPDATE STUDENT SET Marks= 20 WHERE Roll_no = 7;

DELETE FROM STUDENT WHERE Roll_no=4;

CREATE VIEW studentview
AS SELECT * FROM STUDENT;

CREATE INDEX email_ind
ON STUDENT (Email_id);
select * from USER_INDEXES;

CREATE SEQUENCE stud_seq
INCREMENT BY 1
START WITH 23;
INSERT INTO STUDENT(Roll_no,Name,DeptNo,Marks,Email_id) VALUES(stud_seq.nextval,'Awaze',102,50,'awaze7@gmail.com');
INSERT INTO STUDENT(Roll_no,Name,DeptNo,Marks,Email_id) VALUES(stud_seq.nextval,'D',103,130,'D@gmail.com');
DROP SEQUENCE stud_seq;

CREATE SYNONYM STUDENT_SYNONYM FOR STUDENT
